final verse

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -74,18 +74,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up SSH key
+     - name: Set up SSH key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
           chmod 600 ~/.ssh/id_ed25519
           eval $(ssh-agent -s)
-          ssh-add ~/.ssh/id_ed25519
-          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+          ssh-add ~/.ssh/id_ed25519 || { echo "Failed to add SSH key"; exit 1; }
+          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || { echo "Failed to scan SSH key"; exit 1; }
+          cat ~/.ssh/id_ed25519  # For debugging, ensure to remove this line after debugging
 
-      - name: Deploy to server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
-            cd /home/mubina/car-wash
-            sudo docker compose up -d --build
-          EOF
