one

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -66,28 +66,27 @@ jobs:
         run: |
           cd service  # Assuming tests are in the "service" directory
           go test ./...
+deploy:
+  runs-on: ubuntu-latest
+  needs: test
+  steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
 
-  deploy:
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    - name: Set up SSH key
+      run: |
+        mkdir -p ~/.ssh
+        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
+        chmod 600 ~/.ssh/id_ed25519
+        eval $(ssh-agent -s)
+        ssh-add -l || { echo "No keys added"; exit 1; }
+        ssh-add ~/.ssh/id_ed25519 || { echo "Failed to add SSH key"; exit 1; }
+        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || { echo "Failed to scan SSH key"; exit 1; }
+        echo "SSH key setup complete"
 
-      - name: Set up SSH key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
-          chmod 600 ~/.ssh/id_ed25519
-          eval $(ssh-agent -s)
-          ssh-add ~/.ssh/id_ed25519 || { echo "Failed to add SSH key"; exit 1; }
-          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || { echo "Failed to scan SSH key"; exit 1; }
-          cat ~/.ssh/id_ed25519  # For debugging, ensure to remove this line after debugging
-
-
-      - name: Deploy to server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
-            cd /home/mubina/car-wash
-            sudo docker compose up -d --build
-          EOF
+    - name: Deploy to server
+      run: |
+        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} << 'EOF'
+          cd /home/mubina/car-wash
+          sudo docker compose up -d --build
+        EOF
